# Generated by Django 5.2.1 on 2025-06-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='owner',
            field=models.CharField(default='senuoy', max_length=100),
        ),
    ]
