# Generated by Django 5.2.1 on 2025-06-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_reward_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='conditions_generales',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='cinema_ticket_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
